#!/bin/bash
#
# This program use to show Moxa HSR/PRP card interface name and pci bus id
#
#

printf "Searching Moxa HSR/PRP card...\n"
for pciid in $(ls /sys/bus/pci/devices/); do
	DEVID=$(cat /sys/bus/pci/devices/$pciid/device)
	if [ "0x10d3" = "$DEVID" ]; then
		NETNAME=$(ls /sys/bus/pci/devices/$pciid/net)
		if [ "$NETNAME" != "" ]; then
			printf "$NETNAME - pcibus id is $pciid\n"
		fi
	fi
done

