#!/bin/bash
#
# This program use to show Moxa HSR/PRP card interface name and pci bus id
#
#

printf "Searching Moxa HSR/PRP card...\n"
for pciid in $(ls /sys/bus/pci/devices/); do
	DEVID=$(cat /sys/bus/pci/devices/$pciid/device)
	if [ x"0x10d3" = x"$DEVID" ]; then
		NETNAME=$(ls /sys/bus/pci/devices/$pciid/net)
		if [ x"$NETNAME" != x"" ]; then
			printf "$NETNAME - pcibus id is $pciid\n"
		fi
	fi
done

